### PR TITLE
WIP: add React rules

### PR DESCRIPTION
**Pull request by geekdada**
Since the Egg is CommonJS structured, the default `sourceType` of this config will still be `script`, but the `sourceType` of React config is set to `module` due to the popularity of Babel. I'm assuming that developers put `extends: egg` in the root of their project as it is used to be, and put `extends: egg/react` in the root of React code folder will be just fine.

The React rules are exactly the same as Airbnb's which is extends from `eslint-config-react`, we can make some changes based on our common practices.

### CODE REVIEW

**Comment by geekdada** [comment]
The ant-design also has a eslint config https://github.com/ant-design/ant-design/blob/master/.eslintrc.js

**Comment by popomore** [comment]
LGTM

**Comment by popomore** [comment]
就是插件没依赖用起来会比较麻烦

**Comment by popomore** [comment]
+ eslint-config-egg@4.0.0

**Pull request merged**
